spring.application.name=TU Connect
spring.profiles.active=dev

# PostgreSQL Database Configuration for application-dev.properties
# UNCOMMENT THESE FOR DEMOS
#spring.datasource.url=jdbc:postgresql://localhost:5432/<DataBase>
#spring.datasource.username=<User>
#spring.datasource.password=<Password>
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# H2 Database Configuration
# ONLY INTENDED FOR USAGE DURING DEVELOPMENT PURPOSES, COMMENT OUT IF USING POSTGRESQL
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration
# 256-bit key (base64 encoded) recommended for HS256
jwt.secret=9a4f2c8d3b7a1e6f4g5h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d
# default expiration time of an hour per session
jwt.expiration=3600000

#Cloudinary Configuration
cloudinary.cloud-name=dxm9f2wne
cloudinary.api-key=572578484963236
cloudinary.api-secret=ODLKekqf8VX_BVS1DBNqFzo6Emo

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB